<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! 1.5 - Open Source Content Management" -->
<feed xmlns="http://www.w3.org/2005/Atom"  xml:lang="ru-ru">
	<title type="text">Для училища</title>
	<subtitle type="text">Сольфеджио. Теория музыки. Анализ. Гармония (решебники)</subtitle>
	<link rel="alternate" type="text/html" href="http://www.lafamire.ru"/>
	<id>http://www.lafamire.ru/index.php</id>
	<updated>2017-05-04T13:24:30Z</updated>
	<generator uri="http://joomla.org" version="1.5">Joomla! 1.5 - Open Source Content Management</generator>
<link rel="self" type="application/atom+xml" href="http://www.lafamire.ru/index.php?option=com_content&amp;view=category&amp;id=41%3A2010-08-26-18-25-45&amp;layout=blog&amp;Itemid=47&amp;format=feed&amp;type=atom" />
	<entry>
		<title>Музыкальная развивающая игра</title>
		<link rel="alternate" type="text/html" href="http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1833:2013-09-10-19-43-46&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=1045"/>
		<published>2013-09-10T19:37:46Z</published>
		<updated>2013-09-10T19:37:46Z</updated>
		<id>http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1833:2013-09-10-19-43-46&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=1045</id>
		<author>
			<name>Гамаюн</name>
		<email>gamayun@lafamire.ru</email>
		</author>
		<summary type="html">&lt;center&gt;&lt;object classid=&quot;clsid:D27CDB6E-AE6D-11cf-96B8-444553540000&quot; codebase=&quot;http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0&quot; height=&quot;373&quot; width=&quot;500&quot;&gt; 
  &lt;param name=&quot;movie&quot; value=&quot;/images/flash/game/musicmatch.swf&quot;&gt; 
  &lt;embed src=&quot;http://www.lafamire.ru//images/flash/game/musicmatch.swf&quot; mce_src=&quot;http://www.lafamire.ru//images/flash/game/musicmatch.swf&quot; quality=&quot;high&quot; pluginspage=&quot;http://www.macromedia.com/go/getflashplayer&quot; type=&quot;application/x-shockwave-flash&quot; height=&quot;373&quot; align=&quot;middle&quot; width=&quot;500&quot;&gt;&lt;/object&gt;
&lt;p&gt;&lt;br /&gt;&lt;br /&gt;Для открытия на весь экран ... нажми &lt;a href=&quot;http://www.lafamire.ru//images/flash/game/musicmatch.swf&quot; target=&quot;_blank&quot; mce_href=&quot;http://www.lafamire.ru//images/flash/game/musicmatch.swf&quot;&gt;сюда&lt;/a&gt;&lt;br mce_bogus=&quot;1&quot;&gt;&lt;/p&gt;&lt;/center&gt;</summary>
		<content type="html">&lt;center&gt;&lt;object classid=&quot;clsid:D27CDB6E-AE6D-11cf-96B8-444553540000&quot; codebase=&quot;http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0&quot; height=&quot;373&quot; width=&quot;500&quot;&gt; 
  &lt;param name=&quot;movie&quot; value=&quot;/images/flash/game/musicmatch.swf&quot;&gt; 
  &lt;embed src=&quot;http://www.lafamire.ru//images/flash/game/musicmatch.swf&quot; mce_src=&quot;http://www.lafamire.ru//images/flash/game/musicmatch.swf&quot; quality=&quot;high&quot; pluginspage=&quot;http://www.macromedia.com/go/getflashplayer&quot; type=&quot;application/x-shockwave-flash&quot; height=&quot;373&quot; align=&quot;middle&quot; width=&quot;500&quot;&gt;&lt;/object&gt;
&lt;p&gt;&lt;br /&gt;&lt;br /&gt;Для открытия на весь экран ... нажми &lt;a href=&quot;http://www.lafamire.ru//images/flash/game/musicmatch.swf&quot; target=&quot;_blank&quot; mce_href=&quot;http://www.lafamire.ru//images/flash/game/musicmatch.swf&quot;&gt;сюда&lt;/a&gt;&lt;br mce_bogus=&quot;1&quot;&gt;&lt;/p&gt;&lt;/center&gt;</content>
	</entry>
	<entry>
		<title>Обзор методики развития абсолютного слуха</title>
		<link rel="alternate" type="text/html" href="http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=350:2010-04-04-14-44-03&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=896"/>
		<published>2010-08-09T14:42:26Z</published>
		<updated>2010-08-09T14:42:26Z</updated>
		<id>http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=350:2010-04-04-14-44-03&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=896</id>
		<author>
			<name>Гамаюн</name>
		<email>gamayun@lafamire.ru</email>
		</author>
		<summary type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Обзор методики развития абсолютного слуха&lt;/span&gt;&lt;br /&gt;&lt;/h1&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Абсолютный слух - самый точный вид определения всех звуковысотных элементов музыкального языка. Что это такое ? Это способность различать звуки разной высоты по их индивидуальной окраске так, например, как вы различаете цвета (красный, белый и т.д.) или запахи, или оттенки настроений и чувств.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Обычно абсолютный слух бывает заложен с рождения, но довольно часто вырабатывается в процессе музыкальных занятий на инструменте (в данном случае очень важно, чтобы инструмент в течение хотя бы пяти лет был постоянно правильно настроен).&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Методики сольфеджио, в которых последовательно проходятся сначала тональности, располагающиеся на белых клавишах (До мажор, ля минор), а потом добавляются постепенно черные клавиши - фа-диез, до-диез, си-бемоль, ми-бемоль и т.д., способствуют запоминанию тембров сначала белых, а затем черных клавиш.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Что нужно, чтобы начать определять абсолютную высоту звуков? Вслушаться в звуки и определить, чем они отличаются.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Нажмите на фортепиано не торопясь мажорные трезвучия на белых клавишах (до-ми-соль, фа-ля-до, соль-си-ре) как аккорды и вслушайтесь в  их разную окраску. (Особенно прислушайтесь к среднему звуку). Поиграйте их в разных октавах. В какой-бы октаве Вы ни нажали определенное трезвучие (например, Фа-мажорное), его окраска все равно сохранится. Для меня Фа-мажорное трезвучие звучит неярко, матово, пастельно, ассоциируется с тембром деревянно-духовых инструментов из-за  звука фа. Соль мажорное - &quot;струнно-скрипично&quot; из-за сочетания звуков соль и си.  До мажорное - жестко и упруго из-за ноты до и по-деловому задорно из-за нот до и ми.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Эти 3 мажорных трезвучия в До мажоре находятся между собой в зависимости как &quot;тоника, субдоминанта и доминанта.&quot; Гармонизация мелодии &quot;этими&quot; трезвучиями - распространенное явление во всей европейской музыке.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Начните подбирать мелодию с аккомпанементом к советскому киносериалу &quot;Приключения Шерлока Холмса и доктора Ватсона&quot;. Мелодия начинается так: до, до-ми-соль-вверх до-си-ля-си-до. Подберите мелодию (до ноты &quot;ми)&quot; и аккомпанемент,  используя эти 3 мажорных трезвучия.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Нажмите на фортепиано мажорные трезвучия с черной клавишей посередине (ля-до-диез-ми, ре-фа-диез-ля, ми-соль-диез-си). Попробуйте подобрать для них определения. Для меня Ля мажорное трезвучие звучит звонко и &quot;медно-трубно&quot; из-за звуков ля и до-диез. Ре мажорное  - светло, тепло из-за звуков ре и фа-диез и пушисто из-за звука фа-диез. Ми мажорное трезвучие почему-то кажется зеленым  и густым, как елка, из-за нот ми и соль-диез.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Нажмите на фортепиано минорные трезвучия с черной клавишей посередине: до-ми-бемоль-соль, фа-ля-бемоль-до, соль-си-бемоль-ре. Какие слова Вы подобрали бы к ним? Соль минорное трезвучие у меня ассоциируется с дождем, навевающим глубокую печаль и с потоком слез. Фа минорное трезвучие - мягкое из-за нот фа и ля-бемоль и  печальное, как бы в приглушенном свете. До минорное трезвучие - жесткое из-за ноты до и трагическое из-за нот до и ми-бемоль.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Это только мои ощущения тональностей, каждый находит в индивидуальной окраске звуков и трезвучий свои ощущения. Вот когда Вы их найдете, считайте, что приобрели абсолютный слух.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;&lt;a href=&quot;http://www.lafamire.ru/index.php?option=com_content&amp;amp;view=article&amp;amp;id=1187&amp;amp;catid=41&amp;amp;Itemid=73&quot;&gt;З&lt;/a&gt;&lt;a href=&quot;http://www.lafamire.ru/index.php?option=com_content&amp;amp;view=article&amp;amp;id=1187&amp;amp;catid=41&amp;amp;Itemid=73&quot;&gt;десь&lt;/a&gt; появились  упражнения для развития абсолютного слуха. Также можете подбирать на фортепиано &lt;a href=&quot;http://www.lafamire.ru/index.php?option=com_content&amp;amp;view=article&amp;amp;id=737&amp;amp;catid=13&amp;amp;Itemid=15&quot;&gt;мелодии с аккомпанементом.&lt;/a&gt; Это должно сильно помочь для развития относительного слуха и в какой-то степени помочь овладеть абсолютным.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Развитие слуха.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt; &lt;/p&gt;</summary>
		<content type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Обзор методики развития абсолютного слуха&lt;/span&gt;&lt;br /&gt;&lt;/h1&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Абсолютный слух - самый точный вид определения всех звуковысотных элементов музыкального языка. Что это такое ? Это способность различать звуки разной высоты по их индивидуальной окраске так, например, как вы различаете цвета (красный, белый и т.д.) или запахи, или оттенки настроений и чувств.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Обычно абсолютный слух бывает заложен с рождения, но довольно часто вырабатывается в процессе музыкальных занятий на инструменте (в данном случае очень важно, чтобы инструмент в течение хотя бы пяти лет был постоянно правильно настроен).&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Методики сольфеджио, в которых последовательно проходятся сначала тональности, располагающиеся на белых клавишах (До мажор, ля минор), а потом добавляются постепенно черные клавиши - фа-диез, до-диез, си-бемоль, ми-бемоль и т.д., способствуют запоминанию тембров сначала белых, а затем черных клавиш.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Что нужно, чтобы начать определять абсолютную высоту звуков? Вслушаться в звуки и определить, чем они отличаются.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Нажмите на фортепиано не торопясь мажорные трезвучия на белых клавишах (до-ми-соль, фа-ля-до, соль-си-ре) как аккорды и вслушайтесь в  их разную окраску. (Особенно прислушайтесь к среднему звуку). Поиграйте их в разных октавах. В какой-бы октаве Вы ни нажали определенное трезвучие (например, Фа-мажорное), его окраска все равно сохранится. Для меня Фа-мажорное трезвучие звучит неярко, матово, пастельно, ассоциируется с тембром деревянно-духовых инструментов из-за  звука фа. Соль мажорное - &quot;струнно-скрипично&quot; из-за сочетания звуков соль и си.  До мажорное - жестко и упруго из-за ноты до и по-деловому задорно из-за нот до и ми.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Эти 3 мажорных трезвучия в До мажоре находятся между собой в зависимости как &quot;тоника, субдоминанта и доминанта.&quot; Гармонизация мелодии &quot;этими&quot; трезвучиями - распространенное явление во всей европейской музыке.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Начните подбирать мелодию с аккомпанементом к советскому киносериалу &quot;Приключения Шерлока Холмса и доктора Ватсона&quot;. Мелодия начинается так: до, до-ми-соль-вверх до-си-ля-си-до. Подберите мелодию (до ноты &quot;ми)&quot; и аккомпанемент,  используя эти 3 мажорных трезвучия.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Нажмите на фортепиано мажорные трезвучия с черной клавишей посередине (ля-до-диез-ми, ре-фа-диез-ля, ми-соль-диез-си). Попробуйте подобрать для них определения. Для меня Ля мажорное трезвучие звучит звонко и &quot;медно-трубно&quot; из-за звуков ля и до-диез. Ре мажорное  - светло, тепло из-за звуков ре и фа-диез и пушисто из-за звука фа-диез. Ми мажорное трезвучие почему-то кажется зеленым  и густым, как елка, из-за нот ми и соль-диез.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Нажмите на фортепиано минорные трезвучия с черной клавишей посередине: до-ми-бемоль-соль, фа-ля-бемоль-до, соль-си-бемоль-ре. Какие слова Вы подобрали бы к ним? Соль минорное трезвучие у меня ассоциируется с дождем, навевающим глубокую печаль и с потоком слез. Фа минорное трезвучие - мягкое из-за нот фа и ля-бемоль и  печальное, как бы в приглушенном свете. До минорное трезвучие - жесткое из-за ноты до и трагическое из-за нот до и ми-бемоль.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Это только мои ощущения тональностей, каждый находит в индивидуальной окраске звуков и трезвучий свои ощущения. Вот когда Вы их найдете, считайте, что приобрели абсолютный слух.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;&lt;a href=&quot;http://www.lafamire.ru/index.php?option=com_content&amp;amp;view=article&amp;amp;id=1187&amp;amp;catid=41&amp;amp;Itemid=73&quot;&gt;З&lt;/a&gt;&lt;a href=&quot;http://www.lafamire.ru/index.php?option=com_content&amp;amp;view=article&amp;amp;id=1187&amp;amp;catid=41&amp;amp;Itemid=73&quot;&gt;десь&lt;/a&gt; появились  упражнения для развития абсолютного слуха. Также можете подбирать на фортепиано &lt;a href=&quot;http://www.lafamire.ru/index.php?option=com_content&amp;amp;view=article&amp;amp;id=737&amp;amp;catid=13&amp;amp;Itemid=15&quot;&gt;мелодии с аккомпанементом.&lt;/a&gt; Это должно сильно помочь для развития относительного слуха и в какой-то степени помочь овладеть абсолютным.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt;Развитие слуха.&lt;/p&gt;
&lt;p style=&quot;text-align: justify;&quot;&gt; &lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №5</title>
		<link rel="alternate" type="text/html" href="http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1188:2010-04-04-14-44-03&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=901"/>
		<published>2010-08-09T14:42:26Z</published>
		<updated>2010-08-09T14:42:26Z</updated>
		<id>http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1188:2010-04-04-14-44-03&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=901</id>
		<author>
			<name>Гамаюн</name>
		<email>gamayun@lafamire.ru</email>
		</author>
		<summary type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №5&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика    звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot;    окраску. Упражнения заключаются в узнавании ее в мелодическом и    гармоническом сочетании с другими белыми и черными клавишами.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте клавишу &quot;до&quot; в разных октавах. &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Сыграйте пентахорды в До мажоре, в которые она входит: до-ре-ми-фа-соль, си-до-ре-ми-фа, ля-си-до-ре-ми, соль-ля-си-до-ре, фа-соль-ля-си-до&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;. &lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2.  Попросите  товарища поиграть Вам эти сочетания, а сами отвечайте на  вопрос:  клавиша &quot;до&quot; какая по счету?&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему   Вы не будете ошибаться в ответах на эти вопросы? Потому что Вы в любом   случае отличите звучание  &quot;до&quot; от звучания других клавиш, услышите сочетание си-до, в котором полтона.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;</summary>
		<content type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №5&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика    звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot;    окраску. Упражнения заключаются в узнавании ее в мелодическом и    гармоническом сочетании с другими белыми и черными клавишами.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте клавишу &quot;до&quot; в разных октавах. &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Сыграйте пентахорды в До мажоре, в которые она входит: до-ре-ми-фа-соль, си-до-ре-ми-фа, ля-си-до-ре-ми, соль-ля-си-до-ре, фа-соль-ля-си-до&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;. &lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2.  Попросите  товарища поиграть Вам эти сочетания, а сами отвечайте на  вопрос:  клавиша &quot;до&quot; какая по счету?&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему   Вы не будете ошибаться в ответах на эти вопросы? Потому что Вы в любом   случае отличите звучание  &quot;до&quot; от звучания других клавиш, услышите сочетание си-до, в котором полтона.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №3</title>
		<link rel="alternate" type="text/html" href="http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1185:2010-04-04-14-44-03&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=899"/>
		<published>2010-08-09T14:42:26Z</published>
		<updated>2010-08-09T14:42:26Z</updated>
		<id>http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1185:2010-04-04-14-44-03&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=899</id>
		<author>
			<name>Гамаюн</name>
		<email>gamayun@lafamire.ru</email>
		</author>
		<summary type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №3&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика   звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot;   окраску. Упражнения заключаются в узнавании ее в мелодическом и   гармоническом сочетании с другими белыми и черными клавишами.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте клавишу &quot;до&quot; в разных октавах. &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Сыграйте  трезвучия, в которые она входит в качестве среднего звука: ля-до-ми  (ля-минорное) и ля-бемоль-до-ми-бемоль (ля-бемоль-мажорное). Сыграйте трезвучия, в которые она входит в качестве первого звука: до-ми-соль (до-мажорное) и до-ми-бемоль-соль (до-минорное). Сыграйте трезвучия, в которые она входит в качестве третьего звука: фа-ля-до (фа-мажорное) и фа-ля-бемоль-до (фа-минорное).&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2. Попросите  товарища поиграть Вам эти сочетания, а сами отвечайте на вопросы:  клавиша &quot;до&quot; первая,  вторая или третья по счету, она входит в мажорное или в минорное трезвучие?&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt; Назовите тональность трезвучия.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему  Вы не будете ошибаться в ответах на эти вопросы? Потому что Вы в любом  случае отличите звучание  черных клавиш от звучания белых клавиш. Потому что Вы в любом случае  отличите минорное трезвучие от мажорного.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;</summary>
		<content type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №3&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика   звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot;   окраску. Упражнения заключаются в узнавании ее в мелодическом и   гармоническом сочетании с другими белыми и черными клавишами.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте клавишу &quot;до&quot; в разных октавах. &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Сыграйте  трезвучия, в которые она входит в качестве среднего звука: ля-до-ми  (ля-минорное) и ля-бемоль-до-ми-бемоль (ля-бемоль-мажорное). Сыграйте трезвучия, в которые она входит в качестве первого звука: до-ми-соль (до-мажорное) и до-ми-бемоль-соль (до-минорное). Сыграйте трезвучия, в которые она входит в качестве третьего звука: фа-ля-до (фа-мажорное) и фа-ля-бемоль-до (фа-минорное).&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2. Попросите  товарища поиграть Вам эти сочетания, а сами отвечайте на вопросы:  клавиша &quot;до&quot; первая,  вторая или третья по счету, она входит в мажорное или в минорное трезвучие?&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt; Назовите тональность трезвучия.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему  Вы не будете ошибаться в ответах на эти вопросы? Потому что Вы в любом  случае отличите звучание  черных клавиш от звучания белых клавиш. Потому что Вы в любом случае  отличите минорное трезвучие от мажорного.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №2</title>
		<link rel="alternate" type="text/html" href="http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1186:2010-04-04-14-44-03&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=898"/>
		<published>2010-08-09T14:42:26Z</published>
		<updated>2010-08-09T14:42:26Z</updated>
		<id>http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1186:2010-04-04-14-44-03&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=898</id>
		<author>
			<name>Гамаюн</name>
		<email>gamayun@lafamire.ru</email>
		</author>
		<summary type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №2&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика  звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot;  окраску. Упражнения заключаются в узнавании ее в мелодическом и  гармоническом сочетании с другими белыми и черными клавишами.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте клавишу &quot;до&quot; в разных октавах. &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Сыграйте трезвучия, в которые она входит в качестве среднего звука: ля-до-ми (ля-минорное) и ля-бемоль-до-ми-бемоль (ля-бемоль-мажорное). Теперь сыграйте ее в следующих мелодических сочетаниях: ля-си-до, си-до-ре, до-ре-ми, ля-бемоль-си-бемоль-до, си-бемоль-до-ре-бемоль, до-ре-бемоль-ми-бемоль.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2. Попросите  товарища поиграть Вам эти сочетания, а сами отвечайте на вопросы:  клавиша &quot;до&quot; в сочетании с черными или с белыми клавишами, первая,  вторая или третья по счету?&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему  Вы не будете ошибаться в ответах на эти вопросы?Потому что Вы в любом случае отличите звучание  черных клавиш от звучания белых клавиш. Потому что Вы в любом случае отличите отрезок гаммы ля минора или отрезок гаммы Ля-бемоль мажора.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;/span&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;</summary>
		<content type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №2&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика  звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot;  окраску. Упражнения заключаются в узнавании ее в мелодическом и  гармоническом сочетании с другими белыми и черными клавишами.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте клавишу &quot;до&quot; в разных октавах. &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Сыграйте трезвучия, в которые она входит в качестве среднего звука: ля-до-ми (ля-минорное) и ля-бемоль-до-ми-бемоль (ля-бемоль-мажорное). Теперь сыграйте ее в следующих мелодических сочетаниях: ля-си-до, си-до-ре, до-ре-ми, ля-бемоль-си-бемоль-до, си-бемоль-до-ре-бемоль, до-ре-бемоль-ми-бемоль.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2. Попросите  товарища поиграть Вам эти сочетания, а сами отвечайте на вопросы:  клавиша &quot;до&quot; в сочетании с черными или с белыми клавишами, первая,  вторая или третья по счету?&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему  Вы не будете ошибаться в ответах на эти вопросы?Потому что Вы в любом случае отличите звучание  черных клавиш от звучания белых клавиш. Потому что Вы в любом случае отличите отрезок гаммы ля минора или отрезок гаммы Ля-бемоль мажора.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;/span&gt;&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №1</title>
		<link rel="alternate" type="text/html" href="http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1187:2010-04-04-14-44-03&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=897"/>
		<published>2010-08-09T14:42:26Z</published>
		<updated>2010-08-09T14:42:26Z</updated>
		<id>http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1187:2010-04-04-14-44-03&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=897</id>
		<author>
			<name>Гамаюн</name>
		<email>gamayun@lafamire.ru</email>
		</author>
		<summary type="html">&lt;p style=&quot;text-align: justify;&quot;&gt;Перед упражнениями убедитесь в правильной настройке вашего фортепиано. Для этого послушайте &quot;&lt;a href=&quot;http://www.lafamire.ru/index.php?option=com_content&amp;amp;view=article&amp;amp;id=895&amp;amp;catid=36&amp;amp;Itemid=77&quot;&gt;до-ре-до&lt;/a&gt;&quot; здесь и сравните с ним &quot;до-ре-до&quot; на вашем фортепиано.&lt;/p&gt;
&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №1&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot; окраску. Упражнения заключаются в узнавании ее в мелодическом и гармоническом сочетании с другими белыми и черными клавишами.&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте на фортепиано клавишу &quot;до&quot; в разных октавах.  Теперь сыграйте ее в следующих мелодических сочетаниях: си-до, до-ре, си-бемоль-до, до-ре-бемоль.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Попросите товарища поиграть Вам эти сочетания, а сами отвечайте на вопросы: клавиша &quot;до&quot; в сочетании с черной или с белой клавишей, первая или вторая по счету?&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему Вы не будете ошибаться в ответах на эти вопросы? Потому что си-до-полтона, до-ре- целый тон, си-бемоль-до- целый тон, до-ре-бемоль-полтона. Потому что Вы в любом случае отличите звучание черных клавиш от звучания белых клавиш.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
Развитие слуха.&lt;br /&gt;</summary>
		<content type="html">&lt;p style=&quot;text-align: justify;&quot;&gt;Перед упражнениями убедитесь в правильной настройке вашего фортепиано. Для этого послушайте &quot;&lt;a href=&quot;http://www.lafamire.ru/index.php?option=com_content&amp;amp;view=article&amp;amp;id=895&amp;amp;catid=36&amp;amp;Itemid=77&quot;&gt;до-ре-до&lt;/a&gt;&quot; здесь и сравните с ним &quot;до-ре-до&quot; на вашем фортепиано.&lt;/p&gt;
&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №1&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot; окраску. Упражнения заключаются в узнавании ее в мелодическом и гармоническом сочетании с другими белыми и черными клавишами.&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте на фортепиано клавишу &quot;до&quot; в разных октавах.  Теперь сыграйте ее в следующих мелодических сочетаниях: си-до, до-ре, си-бемоль-до, до-ре-бемоль.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Попросите товарища поиграть Вам эти сочетания, а сами отвечайте на вопросы: клавиша &quot;до&quot; в сочетании с черной или с белой клавишей, первая или вторая по счету?&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему Вы не будете ошибаться в ответах на эти вопросы? Потому что си-до-полтона, до-ре- целый тон, си-бемоль-до- целый тон, до-ре-бемоль-полтона. Потому что Вы в любом случае отличите звучание черных клавиш от звучания белых клавиш.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
Развитие слуха.&lt;br /&gt;</content>
	</entry>
	<entry>
		<title>Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №4</title>
		<link rel="alternate" type="text/html" href="http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1184:2010-04-04-14-44-03&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=900"/>
		<published>2010-08-09T14:42:26Z</published>
		<updated>2010-08-09T14:42:26Z</updated>
		<id>http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1184:2010-04-04-14-44-03&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=900</id>
		<author>
			<name>Гамаюн</name>
		<email>gamayun@lafamire.ru</email>
		</author>
		<summary type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №4&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика    звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot;    окраску. Упражнения заключаются в узнавании ее в мелодическом и    гармоническом сочетании с другими белыми и черными клавишами.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте клавишу &quot;до&quot; в разных октавах. &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Сыграйте   терции, в которые она входит в качестве &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;верхнего&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt; звука: ля-до-   (ля-минорная) и ля-бемоль-до (ля-бемоль-мажорная). Сыграйте  терции, в которые она входит в качестве &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;нижнего&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt; звука: до-ми  (до-мажорная) и до-ми-бемоль (до-минорная). &lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2.  Попросите  товарища поиграть Вам эти сочетания, а сами отвечайте на  вопросы:  клавиша &quot;до&quot; первая или &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;вторая&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt; по счету, она в сочетании с белой или с черной клавишей? Она входит в большую или в малую терцию?&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt; Назовите ноты терций.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему   Вы не будете ошибаться в ответах на эти вопросы? Потому что Вы в любом   случае отличите звучание  &quot;до&quot; от звучания других клавиш, звучание черных клавиш от звучания белых клавиш.  Потому что Вы в любом случае  отличите малую терцию от большой.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;</summary>
		<content type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №4&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика    звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot;    окраску. Упражнения заключаются в узнавании ее в мелодическом и    гармоническом сочетании с другими белыми и черными клавишами.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте клавишу &quot;до&quot; в разных октавах. &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Сыграйте   терции, в которые она входит в качестве &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;верхнего&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt; звука: ля-до-   (ля-минорная) и ля-бемоль-до (ля-бемоль-мажорная). Сыграйте  терции, в которые она входит в качестве &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;нижнего&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt; звука: до-ми  (до-мажорная) и до-ми-бемоль (до-минорная). &lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2.  Попросите  товарища поиграть Вам эти сочетания, а сами отвечайте на  вопросы:  клавиша &quot;до&quot; первая или &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;вторая&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt; по счету, она в сочетании с белой или с черной клавишей? Она входит в большую или в малую терцию?&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt; Назовите ноты терций.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему   Вы не будете ошибаться в ответах на эти вопросы? Потому что Вы в любом   случае отличите звучание  &quot;до&quot; от звучания других клавиш, звучание черных клавиш от звучания белых клавиш.  Потому что Вы в любом случае  отличите малую терцию от большой.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №6</title>
		<link rel="alternate" type="text/html" href="http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1252:-qq-6&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=902"/>
		<published>2010-08-09T14:42:26Z</published>
		<updated>2010-08-09T14:42:26Z</updated>
		<id>http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1252:-qq-6&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=902</id>
		<author>
			<name>Гамаюн</name>
		<email>gamayun@lafamire.ru</email>
		</author>
		<summary type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №6&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика    звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot;    окраску. Упражнения заключаются в узнавании ее в мелодическом и    гармоническом сочетании с другими белыми и черными клавишами.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте клавишу &quot;до&quot; в разных октавах. &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Сыграйте пентахорды в Ля-бемоль мажоре, в которые она входит: до-реb-миb-фа-соль, сиb-до-реb-миb-фа, ляb-сиb-до-реb-миb, соль-ляb-сиb-до-реb, фа-соль-ляb-сиb-до&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;. &lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2.  Попросите  товарища поиграть Вам эти сочетания, а сами отвечайте на  вопрос:  клавиша &quot;до&quot; какая по счету?&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему   Вы не будете ошибаться в ответах на эти вопросы? Потому что Вы в любом   случае отличите звучание  &quot;до&quot; от звучания других клавиш, услышите сочетание до-реb, в котором полтона. &lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;</summary>
		<content type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №6&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика    звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot;    окраску. Упражнения заключаются в узнавании ее в мелодическом и    гармоническом сочетании с другими белыми и черными клавишами.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте клавишу &quot;до&quot; в разных октавах. &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Сыграйте пентахорды в Ля-бемоль мажоре, в которые она входит: до-реb-миb-фа-соль, сиb-до-реb-миb-фа, ляb-сиb-до-реb-миb, соль-ляb-сиb-до-реb, фа-соль-ляb-сиb-до&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;. &lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2.  Попросите  товарища поиграть Вам эти сочетания, а сами отвечайте на  вопрос:  клавиша &quot;до&quot; какая по счету?&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему   Вы не будете ошибаться в ответах на эти вопросы? Потому что Вы в любом   случае отличите звучание  &quot;до&quot; от звучания других клавиш, услышите сочетание до-реb, в котором полтона. &lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №7</title>
		<link rel="alternate" type="text/html" href="http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1256:-qq-7&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=903"/>
		<published>2010-08-09T14:42:26Z</published>
		<updated>2010-08-09T14:42:26Z</updated>
		<id>http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1256:-qq-7&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=903</id>
		<author>
			<name>Гамаюн</name>
		<email>gamayun@lafamire.ru</email>
		</author>
		<summary type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №7&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика    звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot;    окраску. Упражнения заключаются в узнавании ее в мелодическом и    гармоническом сочетании с другими белыми и черными клавишами.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте клавишу &quot;до&quot; в разных октавах. &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Сыграйте трихорды в До мажоре, в которые она входит: соль-си-до, ля-до-ре, до-ми-фа, соль-ля-до, си-до-ми, до-ре-фа&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;. &lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2.  Попросите  товарища поиграть Вам эти сочетания, а сами отвечайте на  вопросы: Клавиша &quot;до&quot; какая по счету? Назовите весь трихорд.&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему   Вы не будете ошибаться в ответах на эти вопросы? Потому что Вы в любом   случае отличите звучание  &quot;до&quot; от звучания других клавиш, услышите сочетание интервалов  - секунда-терция  либо терция-секунда. &lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;</summary>
		<content type="html">&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуком &quot;до&quot; №7&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика    звука &quot;до&quot;: белая клавиша, имеющая своеобразную по звуку &quot;пустую&quot;    окраску. Упражнения заключаются в узнавании ее в мелодическом и    гармоническом сочетании с другими белыми и черными клавишами.&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте клавишу &quot;до&quot; в разных октавах. &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Сыграйте трихорды в До мажоре, в которые она входит: соль-си-до, ля-до-ре, до-ми-фа, соль-ля-до, си-до-ми, до-ре-фа&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;. &lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2.  Попросите  товарища поиграть Вам эти сочетания, а сами отвечайте на  вопросы: Клавиша &quot;до&quot; какая по счету? Назовите весь трихорд.&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему   Вы не будете ошибаться в ответах на эти вопросы? Потому что Вы в любом   случае отличите звучание  &quot;до&quot; от звучания других клавиш, услышите сочетание интервалов  - секунда-терция  либо терция-секунда. &lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Упражнения для развития абсолютного слуха. Упражнение со звуками &quot;до&quot; и &quot;до-диез&quot; №8</title>
		<link rel="alternate" type="text/html" href="http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1353:-qq-q-q-8&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=904"/>
		<published>2010-08-09T14:42:26Z</published>
		<updated>2010-08-09T14:42:26Z</updated>
		<id>http://www.lafamire.ru/index.php?option=com_content&amp;view=article&amp;id=1353:-qq-q-q-8&amp;catid=41:2010-08-26-18-25-45&amp;Itemid=904</id>
		<author>
			<name>Гамаюн</name>
		<email>gamayun@lafamire.ru</email>
		</author>
		<summary type="html">&lt;p style=&quot;text-align: justify;&quot;&gt;Перед упражнениями убедитесь в правильной настройке вашего фортепиано. Для этого послушайте &quot;&lt;a href=&quot;http://www.lafamire.ru/index.php?option=com_content&amp;amp;view=article&amp;amp;id=895&amp;amp;catid=36&amp;amp;Itemid=77&quot;&gt;до-ре-до&lt;/a&gt;&quot; здесь и сравните с ним &quot;до-ре-до&quot; на вашем фортепиано.&lt;/p&gt;
&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуками &quot;до&quot; и &quot;до-диез&quot; №8&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика звука &quot;до-диез&quot;: черная клавиша, имеющая своеобразную по звуку &quot;звонкую&quot; окраску. Упражнение заключается в узнавании &lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&quot;до&quot; и &quot;до-диез&quot; в мелодическом сочетании с другими белыми клавишами.&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте на фортепиано клавиши &quot;до&quot; и &quot;до-диез&quot; в разных октавах.  Теперь сыграйте следующие мелодические сочетания: си-до, до-ре, си-до-диез, до-диез-ре.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2. Попросите товарища поиграть Вам эти сочетания, а сами отвечайте на вопросы: содержит ли сочетание черную клавишу? если содержит, то черная клавиша первая или вторая по счету? назовите мелодическое сочетание.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему Вы не будете ошибаться в ответах на эти вопросы? Потому что си-до-полтона, до-ре- целый тон, &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;си-до-диез&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;- целый тон, &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;до-диез-ре&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;-полтона. Потому что Вы в любом случае отличите звучание черных клавиш от звучания белых клавиш.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;br /&gt;</summary>
		<content type="html">&lt;p style=&quot;text-align: justify;&quot;&gt;Перед упражнениями убедитесь в правильной настройке вашего фортепиано. Для этого послушайте &quot;&lt;a href=&quot;http://www.lafamire.ru/index.php?option=com_content&amp;amp;view=article&amp;amp;id=895&amp;amp;catid=36&amp;amp;Itemid=77&quot;&gt;до-ре-до&lt;/a&gt;&quot; здесь и сравните с ним &quot;до-ре-до&quot; на вашем фортепиано.&lt;/p&gt;
&lt;h1 style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Упражнения для развития абсолютного слуха. Упражнение со звуками &quot;до&quot; и &quot;до-диез&quot; №8&lt;/span&gt;&lt;/h1&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;Характеристика звука &quot;до-диез&quot;: черная клавиша, имеющая своеобразную по звуку &quot;звонкую&quot; окраску. Упражнение заключается в узнавании &lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&quot;до&quot; и &quot;до-диез&quot; в мелодическом сочетании с другими белыми клавишами.&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;1. Сыграйте на фортепиано клавиши &quot;до&quot; и &quot;до-диез&quot; в разных октавах.  Теперь сыграйте следующие мелодические сочетания: си-до, до-ре, си-до-диез, до-диез-ре.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;2. Попросите товарища поиграть Вам эти сочетания, а сами отвечайте на вопросы: содержит ли сочетание черную клавишу? если содержит, то черная клавиша первая или вторая по счету? назовите мелодическое сочетание.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Почему Вы не будете ошибаться в ответах на эти вопросы? Потому что си-до-полтона, до-ре- целый тон, &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;си-до-диез&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;- целый тон, &lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;до-диез-ре&lt;/span&gt;&lt;/span&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;-полтона. Потому что Вы в любом случае отличите звучание черных клавиш от звучания белых клавиш.&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 14pt;&quot;&gt;&lt;span style=&quot;font-size: 12pt;&quot;&gt;Развитие слуха.&lt;br /&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;br /&gt;</content>
	</entry>
</feed>
